[package]
name = "watch-rs"
version = "0.2.0"
description = "A Rust implementation of Linux's `watch` with extended features"
edition = "2021"
rust-version = "1.85"
authors = ["DrEsteban"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/DrEsteban/watch-rust"
categories = ["command-line-utilities"]
exclude = [
    ".github",
    ".vscode"
]

[package.metadata.wix]
year = "2026"

[dependencies]
anstyle-parse = "1.0.0"
chrono = { version = "0.4.45", default-features = false, features = ["clock", "std"] }
clap = { version = "4.6.4", features = ["derive", "cargo", "env"] }
crossterm = { version = "0.29.0", default-features = false, features = ["events", "windows"] }
unicode-width = "0.2.2"

[[bin]]
name = "watchr"
path = "src/main.rs"
