name: Publish package

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-release
      run: cargo install cargo-release
    - name: Build & Test
      run: |
        cargo build --verbose
        cargo test --verbose
    - name: Publish
      run: |
        cargo login ${{ secrets.CRATES_IO_TOKEN }}
        cargo release patch --execute --no-confirm --push-remote origin --verbose
